CREATE TABLE IF NOT EXISTS rating(
    rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(5),
    description VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS films(
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    description varchar(200) NOT NULL,
    release date NOT NULL,
    duration integer NOT NULL,
    rating_id integer REFERENCES rating ON DELETE SET NULL,
    CONSTRAINT duration_positive CHECK(duration > 0)
);

CREATE TABLE IF NOT EXISTS genre(
    genre_id INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS users(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(50),
    login VARCHAR(30),
    name VARCHAR(30),
    birthday date
);

CREATE TABLE IF NOT EXISTS status(
    status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS friendship(
    user_id INTEGER REFERENCES users,
    friend_id INTEGER REFERENCES users,
    PRIMARY KEY(user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS films_genres(
    film_id INTEGER REFERENCES films ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genre,
    PRIMARY KEY(film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS likes(
    user_id INTEGER REFERENCES users ON DELETE CASCADE,
    film_id INTEGER REFERENCES films ON DELETE CASCADE,
    like_date DATE,
    PRIMARY KEY (user_id, film_id)
);

